- name: Add users
  user: name={{ item.key }} state={{ item.value.state }} uid={{ item.value.uid }} shell={{ item.value.shell }} password={{ item.value.password }} update_password=on_create
  with_dict: users
# tasks file for jenkins
